language: python
python:
  - "2.7"
sudo: required
dist: trusty
cache: pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy python-scipy python-pandas
  - sudo apt-get install -y python-h5py
  - sudo pip install functools32
script: python -m unittest discover
branches:
  only:
    - master
