language: python
python:
  - "2.7"
dist: trusty
addons:
  apt:
    packages:
      - python-pandas python-h5py
install:
  - pip install functools32
script:
  - python -m unittest discover
branches:
  only:
    - master
