language: python
python:
  - "2.7"
dist: trusty
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pandas python-h5py
install:
  - pip install functools32
script:
  - python -m unittest discover
branches:
  only:
    - master
